### ISSUE TITLE
Awesome mod, a little concern about DC

### ISSUE THREAD

**Issue by Stormchant** [V0idhead/WOTRNineSwords#1]
Would it be possible to add half or full character/warblade/martial class level to Maneuver dc?  kinda hard to build crazy strength on a pure warblade to make dc Maneuver useful and worthwhile at end game.

**Comment by V0idhead** [comment]
I wanted to stay close to the source material for the beginning to keep it simple.
But I have just added a mythic version of Maneuver Focus that adds your mythic rank to DC.
Please note that I just did a quick test to comfirm it works, I didn't test it thoroughly yet. If you can, let me know if it doesn't properly.

Next I'll work on adding feats for bigger boosts to the DC for specific Disciples (similar to how Spell Focus works), I think that would make the strikes work at the later stages in the game without being too overpowered.

**Comment by Stormchant** [comment]
awesome, many thanks =)

**Comment by V0idhead** [comment]
I just pushed version 1.2 adding a feat for each discipline to further increase the DC and also add a unique effect.
