### ISSUE TITLE
Avalance of Blades + Trick Fate = Game Hang

### ISSUE THREAD

**Issue by Vaeliorin** [V0idhead/WOTRNineSwords#11]
If you have something that allows you to always roll 20s (like Trick Fate) it seems to cause the game to hang, presumably because the game is rolling infinite attacks, since you never miss.

**Comment by V0idhead** [comment]
Sorry about that, I didn't get around to test every Mythic with every ability yet.
I assumed attacks would fail once the target died, breaking the cycle.

Thanks for the report.
