### ISSUE TITLE
Weapon Aptitude

### ISSUE THREAD

**Issue by Deathevan** [V0idhead/WOTRNineSwords#2]
Hi, I've just installed your mod, created a character and added levels using ToyBox for build testing. Everything seems fine so far, **except for Weapon Aptitude which isn't adding Fighter Levels.**

As an extra note, I did fresh install several other feat-adding mods alongside yours (no existing game file using them), though nothing outside ModFinder's list.

Thanks for the great job, I'm still using the class despite this because it looks really fun to play.

![image](https://github.com/user-attachments/assets/2e7c1bc1-3c9e-4706-8116-0422ce206e03)

**Comment by V0idhead** [comment]
fixed in 1.1.
Thanks for reporting!
